feat: 忘れ物登録テストの実装（途中）
KiizanKiizan/Manene pull request #100
Opened 2023-08-05 03:30 UTC by yusei53

途中の段階ですが、一旦PR出しておきます。
installしたファイルや編集したファイルを一気にcommitしてしまったため、見にくいかもしれません。これから気をつけます🙇

2023-08-07 05:33 UTC, yusei53 commented
お手隙の際、ご確認のほどよろしくお願い致します。

2023-08-08 01:44 UTC, ryuhei202 requested changes
コメントしたので修正お願いします！

2023-08-08 01:44 UTC, ryuhei202 commented on tests/lost_articles/lost_articles.spec.ts
> +});
なるほど！これでテストのsetupでページ遷移できるのか！👏

2023-08-08 01:44 UTC, ryuhei202 commented on tests/lost_articles/lost_articles.spec.ts
> +    await page.locator("id=outlined-basic").type("てすとてすと");
このような特定の文字列や数値をファイルの一番上で定数に入れちゃうのがいいと思います！
理由としては複数のテストケースで同じ文字列やIDが使用されており、それらを定数にすることでコードの管理や変更が容易になるからです！
```
const INPUTED_MESSAGE = "テスト"
const INPUTED_MEMBER_ID = 280094
```

2023-08-08 01:44 UTC, ryuhei202 commented on tests/lost_articles/lost_articles.spec.ts
> +test.describe("必要項目が入力されていないと登録ボタンが押せない", () => {
describeで階層化できるのか！

2023-08-08 01:47 UTC, yusei53 commented on tests/lost_articles/lost_articles.spec.ts
> +    await page.locator("id=outlined-basic").type("てすとてすと");
@ryuhei202 確かに！修正します！

2023-08-08 03:08 UTC, yusei53 commented
@ryuhei202 修正しました！ご確認よろしくお願い致します！

2023-08-08 07:37 UTC, ryuhei202 approved these changes
確認しました！ありがとうございます！

2023-08-09 06:30 UTC, merged