feat: UseItemLocationsItemScanの作成
KiizanKiizan/Manene pull request #109
Opened 2023-08-08 01:45 UTC by yusei53

ご確認よろしくお願い致します。

2023-08-09 00:39 UTC, kotaesaki requested changes

2023-08-09 00:39 UTC, kotaesaki commented on app/api/usePatchRequest.ts
> +  TError = AxiosError
q: エラーってAxiosError以外返すことなさそうなのでジェネリクス使う必要なさそうだなと思ったんですが、他に何か返しそうですかね？👀

2023-08-09 00:39 UTC, kotaesaki commented
@yusei53 
releaseブランチ作成していないかも？
マージ先をmainではなく、releaseに向けるようにお願いします！

https://github.com/KiizanKiizan/Manene/wiki/github%E9%81%8B%E7%94%A8%E3%81%AE%E4%BB%95%E6%96%B9

2023-08-09 02:33 UTC, yusei53 commented
@kotaesaki 

レビュー修正しました！
ご確認のほど、よろしくお願い致します。

> @yusei53 releaseブランチ作成していないかも？ マージ先をmainではなく、releaseに向けるようにお願いします！
> 
> releaseは作成してあったので、そのままreleaseに向けるよう修正しておきました！

2023-08-09 03:39 UTC, ryuhei202 commented on app/api/item-location/useItemsShow.ts
> +  id: "number";
@kotaesaki 確かにセグメント分けしちゃうとそこ専用のapiっぽくなりますね〜、apiの中にhooksディレクトリを作ってそこに全部ぶち込んでもいいかもですね！

2023-08-09 23:22 UTC, kotaesaki commented on app/api/item-location/useItemsShow.ts
> +  id: "number";
@ryuhei202 
そうですね！hooksなのかfetchなのかディレクトリで表現してもいいかも！

2023-08-09 23:33 UTC, kotaesaki approved these changes

2023-08-09 23:33 UTC, kotaesaki commented on app/api/item-location/useItemsShow.ts
> +type TGetItemsShow = {
これどこかのタイミングで共通化したいですね！
別タスク作っときました！

https://github.com/KiizanKiizan/Manene/issues/125

2023-08-09 23:33 UTC, kotaesaki commented
ありがとうございます！LGTM!!!!

2023-08-10 00:58 UTC, yusei53 commented
@kotaesaki ご確認ありがとうございます！mergeしてよろしいでしょうか？

2023-08-10 00:58 UTC, ryuhei202 commented on app/api/item-location/useItemsShow.ts
> +  id: "number";
@kotaesaki https://github.com/KiizanKiizan/Manene/issues/126
issue登録しました！

2023-08-10 01:00 UTC, merged