Feature/68 87 ピック済みのアイテムにはチェックが付くようにする
KiizanKiizan/Manene pull request #119
Opened 2023-08-09 06:24 UTC by kojikojiXX

2023-08-11 06:09 UTC, ryuhei202 commented on app/components/common/custom-hook/useDisableBrowserBack.ts
> +  const handleClickOpenBarcodeDialog = () => {
バーコード以外にもどるボタン考慮したダイアログに適応したいので命名変更お願いします！
handleClickOpenDailogで！

2023-08-11 06:48 UTC, ryuhei202 commented on app/components/common/custom-hook/useDisableBrowserBack.ts
> +    setIsDialogOpen,
handleClickOpenDialogがあるなら、handleClickCloseDialogを渡せば良いのでは？
openするときは`handleClickOpenDialog`でいいのに、closeするときは使う側でわざわざsetIsDialogOpen(false)とするのもめんどくさいので！

2023-08-14 00:24 UTC, ryuhei202 requested changes
ありがとうございます！何点かコメントしました！

2023-08-20 08:01 UTC, kojikojiXX commented on app/components/coorde-pick/coorde-pick-list.tsx
>        </Box>
https://github.com/KiizanKiizan/Manene/commit/c64eb9e56b528c2af43c9bb338a6173738d47689 これを今回でも使えると思うんですが、これもcherry pickしたらいいでしょうか？

2023-08-27 11:17 UTC, ryuhei202 commented
@kojikojiXX 確認しました！修正終わったらコメント残しておいていただけると助かります！

2023-08-28 09:38 UTC, merged