108 itemfetcherとitemlocationcontainer作成 3
KiizanKiizan/Manene pull request #130
Opened 2023-08-12 01:29 UTC by ryuhei202

ご確認お願いします！

https://github.com/KiizanKiizan/Manene/assets/105505578/0bd3f8eb-b6e8-4bc6-b5f7-76365f187721

https://github.com/KiizanKiizan/Manene/assets/105505578/ba57a90b-dd06-479f-8c39-bc755cacbcfd

https://github.com/KiizanKiizan/Manene/assets/105505578/b871ccc6-30f7-4d4a-86f3-1cba159bfe36

2023-08-12 02:08 UTC, yusei53 approved these changes
LGTM!お疲れ様です！さすがです！

2023-08-17 05:49 UTC, ytsumori requested changes
コメントしました！確認お願いします！！

2023-08-17 05:49 UTC, ytsumori commented on app/components/common/custom-hook/useDisableBrowserBack.ts
> +export default function useDisableBrowserBack() {
[IMO]
この実装だとDialogで使うことを前提にしたhooksになるので、dialog以外でも使えるよう
`useDisableBrowserBack(isDisabled: boolean, altCallback: () => void)`のような形にして`isDisabled`がtrueの場合ブラウザバックの代わりに`altCallback`を発火するみたいなものにすると使いやすいなと思いました！

2023-08-17 05:49 UTC, ytsumori commented on app/components/common/button/scan-button.tsx
> +export default function ScanButton({ onScan, title, disabled, color }: TProps) {
[nits]
こんな感じでpropsのdefault値指定できたはずです！！
```
ScanButton({
  onScan,
  title,
  disabled=false,
  color
})
```
こうすると下で`!!disabled`って書く必要なくなると思います！

2023-08-17 05:49 UTC, ytsumori commented on app/components/common/dialog/error-dialog.tsx
> +  );
[IMO]
他のところでエラー時にalertメソッドで対応してる箇所があったので、統一されていた方がエラーとして認識しやすいかなと思いました！（alert使う方がわかりやすそう？）

2023-08-17 05:49 UTC, ytsumori commented on app/components/item_location/item-location-container.tsx
> +              <Typography>棚版: {locationId}</Typography>
[nits] 「棚番」ですね！

2023-08-17 05:49 UTC, ytsumori commented on app/components/item_location/item-location-container.tsx
> +  const canAddSelectedItem = (targetId: number): boolean => {
[nits] booleanとわかりやすいよう、`is`から始まるよう命名してあげるとわかりやすいかと思いました！
```suggestion
  const isItemSelected = (targetId: number): boolean => {
```

2023-08-17 05:49 UTC, ytsumori commented on app/components/item_location/item-location-container.tsx
> +  const onScanItemId = (id: number) => {
[IMO]この関数はイベントハンドラーなので、`handle`から始まる名前で命名してあげるとわかりやすいかと思います！
```suggestion
  const handleItemScan = (id: number) => {
```

2023-08-17 05:49 UTC, ytsumori commented on app/components/item_location/item-location-container.tsx
> +  const [selectedItem, setSelectedItem] = useState<
[nits]配列なので、複数形で命名してあげるとわかりやすいかと思います！
さらに選択済みというよりスキャン済みアイテムなので
```suggestion
  const [scannedItems, setScannedItems] = useState<
```
とするのが良さそうですね！

2023-08-17 05:49 UTC, ytsumori commented on app/components/item_location/item-detail-fetcher.tsx
[nits]フォルダ名がsnakeケースになってしまっているので、kebabケースに統一した方がいいかと思います！

2023-08-17 05:49 UTC, ytsumori commented on app/components/item_location/item-location-container.tsx
> +          <Dialog open fullWidth>
[IMO]`open`propsでダイアログの表示は判定できるので、
```suggestion
        <Dialog open={locationId !== undefined} fullWidth>
```
みたいな感じでいいかなと思いました！

2023-08-17 05:49 UTC, ytsumori commented on app/components/item_location/item-location-container.tsx
> +  const [itemId, setItemId] = useState<number>();
[nits]これが何のitemIdか分かりにくかったので、
```suggestion
  const [selectedItemId, setSelectedItemId] = useState<number>();
```
とするとより分かりやすいかなと思いました！

2023-08-17 05:49 UTC, ytsumori commented on app/components/item_location/item-location-container.tsx
> +  const onClickOk = () => {
[nits] 上でもコメントした`handle`キーワードを使うのがいいかなと思いました！

2023-08-17 05:49 UTC, ytsumori commented on app/components/item_location/item-location-fetcher.tsx
こちらのコンポーネントは何もレンダーしてないので、コンポーネントとして定義する必要はないかと思います！

2023-08-18 05:48 UTC, ryuhei202 commented on app/api/item-location/useItemLocationsItemScan.ts
> +  size?: string;
確かにそうですね！Kotlinのコード見てレスポンスの型作ったんですけど、Javaにはundfinedないんですね！

2023-08-18 06:35 UTC, ryuhei202 commented on app/components/common/button/scan-button.tsx
> +export default function ScanButton({ onScan, title, disabled, color }: TProps) {
たし🦀

2023-08-18 06:35 UTC, ryuhei202 commented on app/components/item_location/item-location-container.tsx
> +  const [itemId, setItemId] = useState<number>();
scanされたitemIdなのでscanedItemIdにしました！

2023-08-18 06:35 UTC, ryuhei202 commented on app/components/item_location/item-location-container.tsx
> +  const onClickOk = () => {
質問なんですけど、今までbayleeafとかフロントを触ってきた時は、handle~として関数を作って、受け取るコンポーネントではonClickとして受け取っていたのですが、この理由を知りたいです！

今回はbuttonのonClickに直接渡すためonCkick~として関数を作りました！

2023-08-18 06:35 UTC, ryuhei202 commented on app/components/item_location/item-location-fetcher.tsx
となるとどのようにしてdataを取得すれば良いのでしょうか？
この前言っていたようにrefetchとか？？

2023-08-18 09:20 UTC, ryuhei202 commented
@ytsumori レビューありがとうございます！修正したので再度確認お願いします！

2023-08-20 23:51 UTC, ytsumori commented on app/components/item_location/item-location-container.tsx
> +  const onClickOk = () => {
@ryuhei202 
> 質問なんですけど、今までbayleeafとかフロントを触ってきた時は、handle~として関数を作って、受け取るコンポーネントではonClickとして受け取っていたのですが、この理由を知りたいです！

主な理由はReact公式のチュートリアルで`onClick`propsに渡す関数に`handleClick`というように命名してるので、それに則った命名にするのが分かりやすいと判断してるからですね！
なので、
* props名：onXXX
* 関数名：handleXXX

とするのがいいかなと思ってます。

ただ、propsで受け取ったものをそのまま渡す場合はonClickをそのまま渡してしまうケースもあるので、厳密なルールとしては設けてないです！（以下みたいに変数名を変更してやると分かりやすそう？）
```
type TProps = {
  onClick: () => void;
}
export default function ClickableComponent ({ onClick: handleClick }: TProps) {
  return (
    <button onClick={handleClick}></button>
  )
}
```

2023-08-21 00:05 UTC, ytsumori commented on app/components/item_location/item-location-fetcher.tsx
@ryuhei202 そうですね、refetch関数を使う形になるかと思います！（なので、`scannedItem`stateも必要なさそうですね！）

2023-08-21 04:59 UTC, ryuhei202 commented on app/components/item_location/item-location-container.tsx
> +  const onClickOk = () => {
理解しました！ありがとうございます！

2023-08-21 06:45 UTC, ryuhei202 commented
@ytsumori レビュー修正完了したので再度確認お願いします！
戻るボタンを考慮したダイアログの作成と、Fetcher層をレンダリングせずにdata取得できるようにしました！

2023-08-28 03:02 UTC, ytsumori approved these changes
@ryuhei202 
ありがとうございます！追加でコメントしましたが、修正したらマージしちゃってください！

2023-08-28 03:53 UTC, ryuhei202 commented
@ytsumori ありがとうございます！修正したのでマージします！

2023-08-28 03:59 UTC, merged