feat: testの作成
KiizanKiizan/Manene pull request #131
Opened 2023-08-12 08:12 UTC by ryuhei202

ご確認お願いします！

2023-08-17 04:31 UTC, kotaesaki requested changes
ありがとうございます！何点か質問しました！

2023-08-17 04:31 UTC, kotaesaki commented on tests/item_location/item_location.spec.ts
> +    "body > section > div.MuiBox-root.css-ncs2ti > div:nth-child(1) > div > div > p"
nits: 何を指しているのかわかりづらいのでコンポーネントにid振った方がいいと思うんですがどう思いますか？👀

2023-08-17 04:31 UTC, kotaesaki commented on tests/item_location/item_location.spec.ts
> +test("同じアイテムを追加すると「このアイテムは既に読み取り済みです」とアラートダイアルグが表示され、アイテムリストに追加されない", async ({
typo: ダイアルグ

2023-08-17 04:31 UTC, kotaesaki commented on package.json
> +    "sharp": "^0.32.4",
q: これ画像処理系ライブラリだと思うんですがなんでいれました？🤔

2023-08-17 04:31 UTC, kotaesaki commented on tests/item_location/item_location.spec.ts
> +  const itemMiniCard_second = page.locator(
nits: スネークケースが混ざってます

2023-08-17 04:31 UTC, kotaesaki commented on tests/item_location/item_location.spec.ts
> +  page.on("dialog", async (dialog) => {
Web APIのダイアログのテスト簡単！

2023-08-20 23:30 UTC, ryuhei202 commented on tests/item_location/item_location.spec.ts
> +    "body > section > div.MuiBox-root.css-ncs2ti > div:nth-child(1) > div > div > p"
確かにcssセレクタで取得するよりそっちの方がいいと思ったので修正しました！

2023-08-20 23:31 UTC, ryuhei202 commented on tests/item_location/item_location.spec.ts
> +test("同じアイテムを追加すると「このアイテムは既に読み取り済みです」とアラートダイアルグが表示され、アイテムリストに追加されない", async ({
修正しました！

2023-08-20 23:32 UTC, ryuhei202 commented on package.json
> +    "sharp": "^0.32.4",
この前なんかワーニングか何かが出た時に追加したんですけど、具体的な理由は忘れました！
なくても正常に動作したので一旦removeしておきます！また何かあったらしっかりと調べます！

2023-08-20 23:32 UTC, ryuhei202 commented
@kotaesaki レビューありがとうございます！修正したので再度確認お願いします！

2023-08-21 08:43 UTC, kotaesaki approved these changes
@ryuhei202 LGTM!!!

2023-08-22 02:56 UTC, merged