Feature/90/118 アイテム詳細画面のテスト実装2
KiizanKiizan/Manene pull request #143
Opened 2023-08-14 09:16 UTC by OHTA1127

ご確認お願いいたします！

2023-08-15 02:41 UTC, ryuhei202 requested changes
ありがとうございます！何点かコメントしたので確認お願いします！

2023-08-15 02:41 UTC, ryuhei202 commented on tests/item_detail/item_detail.spec.ts
> +test.describe("アイテムIDが入力されないとOKを押せず、入力されると押せる", () => {
[nits]親のテスト名が子供のテスト名と被ってしまっているので、親のテスト名は「OKボタンの状態」とかでどうでしょうか？

2023-08-15 02:41 UTC, ryuhei202 commented on tests/item_detail/item_detail.spec.ts
> +  await page.goto("/item_detail");
毎回のテストで`await page.goto("/item_detail")`;しているのでテストの最初に書いちゃいましょう！

`/item_detail/${ITEM_ID}`とかの特定のurlに飛ぶ時だけテスト内に書くといいと思います！

2023-08-15 02:41 UTC, ryuhei202 commented on tests/item_detail/item_detail.spec.ts
> +    )
locationを変数に入れるという形で統一しているなら、これも変数に入れちゃった方がいいですね！

2023-08-15 02:41 UTC, ryuhei202 commented on tests/item_detail/item_detail.spec.ts
> +  const itemId = "497288";
定数は`ITEM_ID`というように大文字スネークケースで！

https://www.javadrive.jp/javascript/var/index3.html#:~:text=user_name%3B%0Alet%20total_score%3B-,%E5%AE%9A%E6%95%B0,-%E5%AE%9A%E6%95%B0%E5%90%8D%E3%81%A7%E3%81%AF

2023-08-18 09:23 UTC, ryuhei202 approved these changes
確認しました！ありがとうございます！
修正終わったらコメントで一声ください！修正したかどうかわからないので🤲

2023-08-21 08:57 UTC, ryuhei202 commented
@OHTA1127 やっぱりcssセレクターで要素取得するところ、ラベルから取得するように変えるようにお願いします！
https://github.com/KiizanKiizan/Manene/pull/131#discussion_r1296658650

2023-08-21 08:58 UTC, ryuhei202 requested changes
要素の取得をlabelを使う
https://github.com/KiizanKiizan/Manene/pull/143#issuecomment-1685927243

2023-08-21 09:54 UTC, OHTA1127 commented
@ryuhei202  ラベルから取得するというのは、page.locatorからpage.getByRoleに変更するって認識で合っていますか？

2023-08-22 02:54 UTC, ryuhei202 commented
@OHTA1127 こちらの確認を！https://github.com/KiizanKiizan/Manene/pull/131/commits/7bb64377b0ec9135e07f78019f0c3c52989fea65

2023-08-25 02:22 UTC, OHTA1127 commented
@ryuhei202 
要素の取得方法をcssセレクターからラベルに変更したので、お時間ある時に確認お願いいたします！

2023-08-28 01:53 UTC, ryuhei202 approved these changes

2023-08-28 01:54 UTC, merged