Revert "Revert "Merge branch 'feature/123/138-stocktakingcontainer作成'…
KiizanKiizan/Manene pull request #150
Opened 2023-08-15 09:01 UTC by ryuhei202

ご確認お願いします！

https://github.com/KiizanKiizan/Manene/assets/105505578/d01c8041-a042-4ad1-a957-0b67798a1244

- [ ] warnigの解消

2023-08-17 03:46 UTC, kotaesaki requested changes
@ryuhei202 
ありがとうございます！質問含めて何点か質問しましたのでご確認お願いします！

2023-08-17 03:46 UTC, kotaesaki commented on app/components/stocktaking/stocktaking-container.tsx
> +  const CHECK_IN_PROGRESS = 0;
IMO: こっちと同じで同じ定数から呼び出した方がいいですね！
https://github.com/KiizanKiizan/Manene/pull/136#discussion_r1296625716

2023-08-17 03:46 UTC, kotaesaki commented on app/components/stocktaking/stocktaking-container.tsx
> +  useEffect(() => {
q: useEffectってどんなタイミングで必要ですか？👀

2023-08-17 03:46 UTC, kotaesaki commented on app/components/stocktaking/stocktaking-container.tsx
> +  const [locations, setLocations] = useState<TLocation[] | null>(
q: locationsがnullになるのはどんなタイミングですか？👀 対象の棚が存在しない場合は空配列ではなく、nullで帰ってくるんでしたっけ？

2023-08-17 03:46 UTC, kotaesaki commented on app/service/toCamelCaseObject.ts
> +    return obj.map((item) => toCamelCaseObject(item));
再帰関数👍

2023-08-21 07:15 UTC, ryuhei202 commented on app/components/stocktaking/stocktaking-container.tsx
> +  const [locations, setLocations] = useState<TLocation[] | null>(
nullで帰ってきて、nullになるのは棚卸しを開始する前です！nullの時は下のボタンが「棚卸しを開始する」になっています

2023-08-21 07:17 UTC, ryuhei202 commented on app/components/stocktaking/stocktaking-container.tsx
> +  useEffect(() => {
別のコンポーネントでrouter.refesh()した時です！refeshは状態を保持しながらdata取得を再度行ってくれるのですが、状態が変わらないためuseEffectでセットし直しています！

2023-08-21 07:19 UTC, ryuhei202 commented
@kotaesaki 修正したので確認お願いします！

2023-08-21 08:31 UTC, kotaesaki approved these changes
@ryuhei202 LGTM!!

2023-08-21 08:31 UTC, kotaesaki commented on app/components/stocktaking/stocktaking-container.tsx
> +  useEffect(() => {
@ryuhei202 
> router.refresh(): Refresh the current route. Making a new request to the server, re-fetching data requests, and re-rendering Server Components. The client will merge the updated React Server Component payload without losing unaffected client-side React (e.g. useState) or browser state (e.g. scroll position).

stateなどは保持したままSCを再レンダーしてくれるんですね！なるほどです！ありがとうございます！

2023-08-21 08:39 UTC, merged