Feature/123/141 stocktakinglocationcontainerpageの作成2
KiizanKiizan/Manene pull request #152
Opened 2023-08-15 10:02 UTC by ryuhei202

ご確認お願いします！

https://github.com/KiizanKiizan/Manene/assets/105505578/cff06b65-f2fd-40ba-8ed8-ade31096ab23

2023-08-17 04:18 UTC, kotaesaki requested changes
ありがとうございます！何点かコメントしました！

2023-08-17 04:18 UTC, kotaesaki commented on app/components/stocktaking-location/stocktaking-location-container.tsx
> +  const MISSING_LOCATION_ID = 1;
nits: Location.tsのようなファイル作ってそこで定数管理した方が管理しやすいと思いました！

2023-08-17 04:18 UTC, kotaesaki commented on app/components/stocktaking-location/stocktaking-location-container.tsx
> +  const ALL_ITEM_TAB_NUMBER = "1";
IMO: tabコンポーネント側でもこれ呼び出した方が整合の観点で良いかと思いました！ついでに他のtabにも定数振っておくといいかも！

2023-08-17 04:18 UTC, kotaesaki commented on app/components/stocktaking-location/stocktaking-location-container.tsx
> +        router.push("/stocktaking");
q: 動画見る限り一覧ページに遷移しても、右上のloaderタップしないと最新の状態に自動でfetchしてこないんですかね？👀

2023-08-21 08:31 UTC, ryuhei202 commented on app/components/stocktaking-location/stocktaking-location-container.tsx
> +        router.push("/stocktaking");
下の行(116)にrouter.refreshを追加したら戻る時ど同時にrefetchできるようになりました！

2023-08-21 08:38 UTC, kotaesaki approved these changes
@ryuhei202 LGTM!!!!

2023-08-21 08:40 UTC, merged