Feature/146/148 itemstatuscontainer page作成
KiizanKiizan/Manene pull request #154
Opened 2023-08-21 09:33 UTC by OHTA1127

2023-08-22 02:52 UTC, ryuhei202 commented
@OHTA1127 デプロイ失敗してるので確認お願いします！

2023-08-23 23:52 UTC, kotaesaki commented
@OHTA1127 
https://github.com/KiizanKiizan/Manene/pull/149 やおそらく棚卸しのタスクで実装した差分も含まれているので確認お願いします！

2023-08-25 03:46 UTC, OHTA1127 commented
@kotaesaki 
棚卸しに関する差分削除したので、確認お願いいたします！

2023-08-25 04:08 UTC, kotaesaki requested changes
@OHTA1127 ありがとうございます！何点かコメントと質問しましたのでご確認お願いします！

2023-08-25 04:08 UTC, kotaesaki commented on app/components/item-status/item-status-container.tsx
> +  const [open, setOpen] = useState(false);
q: このstateってどこで呼び出していますか？👀

2023-08-25 04:08 UTC, kotaesaki commented on app/components/item-status/item-status-container.tsx
> +    const updateItemIds = itemIds.filter((itemId) => !ids?.includes(itemId));
nits: 
?いらなさそう？

```suggestion
    const updateItemIds = itemIds.filter((itemId) => !ids.includes(itemId));
```

2023-08-25 05:11 UTC, OHTA1127 commented on app/components/item-status/item-status-container.tsx
> +        { status: status, itemIds: itemIds },
修正しました！

2023-08-25 05:14 UTC, OHTA1127 commented on app/components/item-status/item-status-container.tsx
> +                  labelId="demo-simple-select-label"
labelId="status-label"に変更しました！

2023-08-25 05:22 UTC, OHTA1127 commented on app/components/item-status/item-status-container.tsx
> +  const [notExistIds, setNotExistIds] = useState<number[]>();
承知しました！

2023-08-25 05:57 UTC, OHTA1127 commented on app/components/item-status/item-status-container.tsx
> +  const [notExistIds, setNotExistIds] = useState<number[]>();
修正しました！

2023-08-25 06:07 UTC, OHTA1127 commented on app/components/item-status/item-status-container.tsx
> +  const [open, setOpen] = useState(false);
存在しないIDが存在した時に表示されるダイアログを表示する際に使用していたと思っていたんですけど、削除したところ動作に問題なかったので、削除します！

2023-08-25 06:09 UTC, OHTA1127 commented on app/components/item-status/item-status-container.tsx
> +    const updateItemIds = itemIds.filter((itemId) => !ids?.includes(itemId));
削除しても動作に影響無かったので削除します🙇‍♂️

2023-08-25 07:13 UTC, OHTA1127 commented
@kotaesaki 
何点か修正しましたので、お時間ある時に確認お願いいたします！

2023-08-25 08:35 UTC, kotaesaki approved these changes
@OHTA1127 LGTM!!!!🎉🎉

2023-08-25 08:57 UTC, merged