Feature/263/276 sizemeasurementseditform作成
KiizanKiizan/Manene pull request #285
Opened 2023-10-31 01:09 UTC by harukafujii13

## 要件

要件がわかるURLを貼り付けてください
https://github.com/KiizanKiizan/Manene/issues/264
SizeMeasurementsEditFormの作成

JiraのURLを貼り付けてください
https://kiizan-kiizan.atlassian.net/browse/LEEAP-4967

## スクリーンショット
<img width="350" alt="Screenshot 2023-10-30 at 6 06 33 PM" src="https://github.com/KiizanKiizan/Manene/assets/111606615/655f9b28-9c18-49c1-8259-ffcd87c3113f">

| before                                     | after                                      |
| ------------------------------------------ | ------------------------------------------ |
| <img width="250" alt=""> | <img width="250" alt=""> |

## 関連タスク

2023-10-31 01:12 UTC, ryuhei202 requested changes

2023-10-31 01:12 UTC, ryuhei202 commented on app/_components/size_measurements/[id]/Size-measurements-edit-form.tsx
> +            スッキプ
スッキプ😇

2023-10-31 01:17 UTC, harukafujii13 commented
https://github.com/coderabbitai

2023-10-31 01:21 UTC, harukafujii13 commented on app/_components/size_measurements/[id]/Size-measurements-edit-form.tsx
> +            スッキプ
修正しました🥲🙏🏻

2023-10-31 04:09 UTC, ryuhei202 requested changes
何点かコメントしたので確認お願いします！
全体的にできるだけsxを使わないようにして、存在するpropsに入れるのがいいと思いました！
それと、sx内でidとかクラス参照してcssを書かなくてもMUIで実現できると思います！
(↓こういうやつ)
```
{
              m: 1,
              minWidth: 120,
              bgcolor: "white",
              "& .MuiFilledInput-underline:before": {
                display: "none",
              },
              "& .MuiFilledInput-underline:after": {
                display: "none",
              },
```

2023-10-31 04:09 UTC, ryuhei202 commented on app/_components/size_measurements/[id]/Size-measurements-edit-form.tsx
> +              },
Androidで触るのでホバーアクションはいらないと思います！

2023-10-31 04:09 UTC, ryuhei202 commented on app/_components/size_measurements/[id]/Size-measurements-edit-form.tsx
> +          </Button>
確定ボタンが青色になってなさそうなので確認お願いします！

2023-10-31 04:09 UTC, ryuhei202 commented on app/_components/size_measurements/[id]/Size-measurements-edit-form.tsx
> +        />
ListItemの方でレビューするべきだったかもしれませんが、縦幅がやっぱり画像より大きく見えるので修正お願いしたいです！

2023-10-31 04:09 UTC, ryuhei202 commented on app/_components/size_measurements/[id]/Size-measurements-edit-form.tsx
> +                color: "808080",
[IMO]808080とかだと具体的に何色かわからないので定数に入れるといいと思いました！
それか、providersのthemeOptionsに追加するのもいいと思います！

2023-11-05 02:48 UTC, ryuhei202 commented
@kotaesaki @ytsumori 

こちら完了したので確認お願いします！
左：今回の実装、右：Androidの画面
<img width="324" alt="スクリーンショット 2023-11-05 11 33 09" src="https://github.com/KiizanKiizan/Manene/assets/105505578/22f72684-e6eb-46ba-ac85-1e1f868ddbb4">. <img width="335" alt="スクリーンショット 2023-11-05 11 45 53" src="https://github.com/KiizanKiizan/Manene/assets/105505578/8ca922c3-15e3-4789-abcb-25cf4a2b9af3">

2023-11-06 01:10 UTC, kotaesaki approved these changes
ありがとうございます！

2023-11-06 01:10 UTC, kotaesaki commented on app/_components/size_measurements/[id]/Size-measurements-edit-form.tsx
ファイル名頭大文字になってるので、全部小文字の方が良さそうですね！

2023-11-06 01:16 UTC, ryuhei202 commented on app/_components/size_measurements/[id]/Size-measurements-edit-form.tsx
> +          <Typography variant="h6">の測定</Typography>
「の計測」やん

2023-11-06 02:10 UTC, merged