[WIP]Feature/leeap 5039 front manene アイテムサイズcontainer,page実装
KiizanKiizan/manene pull request #293
Opened 2023-11-15 03:43 UTC by ryuhei202

## 要件

要件がわかるURLを貼り付けてください

JiraのURLを貼り付けてください

## スクリーンショット

| before                                     | after                                      |
| ------------------------------------------ | ------------------------------------------ |
| <img width="250" alt=""> | <img width="250" alt=""> |

## 関連タスク

2023-11-18 06:54 UTC, ryuhei202 commented on app/_api/items/itemsShowResponse.ts
apiのレスポンスの型を修正

2023-11-18 06:54 UTC, ryuhei202 commented on app/_api/size_measurement/fetchSizeCalcIndex.tsx
apiレスポンスの型を修正

2023-11-18 06:54 UTC, ryuhei202 commented on app/_api/size_measurement/fetchSizeStableShow.tsx
型名を修正

2023-11-18 06:54 UTC, ryuhei202 commented on app/_api/size_measurement/getSizeMeasurementIndex.tsx
型名を修正

2023-11-18 06:54 UTC, ryuhei202 commented on app/_api/size_measurement/getSizeStableShow.tsx
必要ない関数ファイルだったため消去

2023-11-18 06:54 UTC, ryuhei202 commented on app/_api/size_measurement/useSizeMeasurementUpdate.tsx
型修正

2023-11-18 06:54 UTC, ryuhei202 commented on app/_components/common/Item/item-detail-card-container.tsx
受け取るpropsを修正

2023-11-18 06:56 UTC, ryuhei202 commented
@kojikojiXX レビューお願いします！

2023-11-21 01:00 UTC, ytsumori requested changes
ありがとうございます！コメントしたので確認お願いします！

2023-11-21 01:00 UTC, ytsumori commented on app/_components/common/Item/item-detail-card-container.tsx
> +  withButton,
[IMO]
ボタンはItemCardの外側に位置するUIなので、ItemDetailコンポーネントにその情報は渡さずItemDetailとその下にボタンを設置するコンポーネントを作れば、より汎用性の高いコンポーネントとして残しておけるかなと思いました！

2023-11-21 02:40 UTC, kojikojiXX commented on app/_components/size_measurements/[id]/size-measurement-edit-container.tsx
> +  const [formData, dispatch] = useReducer(formReducer, initialFormData);
useReducerの使い方、勉強になりましたー

2023-11-22 02:45 UTC, ryuhei202 commented
@ytsumori 修正しました！再度確認お願いします！

2023-11-22 02:48 UTC, ytsumori commented on app/_components/common/Item/item-detail-card.tsx
> +  withButton,
@ryuhei202 
`withButton`propsはもう必要なさそう？

2023-11-22 02:54 UTC, ryuhei202 commented on app/_components/common/Item/item-detail-card.tsx
> +  withButton,
https://github.com/KiizanKiizan/manene/blob/a18d14655587406ab5a3196b1598d0c58cc7ffe0/app/_components/common/Item/item-detail-card.tsx#L201
`withButton`propsでスタイル指定しているので残しました！

2023-11-22 02:57 UTC, ryuhei202 commented on app/_components/common/Item/item-detail-card.tsx
> +  withButton,
@ytsumori 
withButtonがないやつ(棚移動)
<img width="400" alt="スクリーンショット 2023-11-22 11 55 16" src="https://github.com/KiizanKiizan/manene/assets/105505578/68cf0c3c-89cc-47f6-bfb1-0fb16ba1d574">
withButtonがあるやつ(サイズ計測)
<img width="400" alt="スクリーンショット 2023-11-22 11 55 42" src="https://github.com/KiizanKiizan/manene/assets/105505578/d0b05d20-b25d-4805-bb80-b1bf0fdd9b53">

2023-11-22 02:58 UTC, ytsumori commented on app/_components/common/Item/item-detail-card.tsx
> +  withButton,
@ryuhei202 
なるほど
だとするとそもそもスタイルの割り当て方があんまり適切じゃないかもですね！
ダイアログの高さを`maxHeight`などで画面に収まるように設定して、`ItemDetailCard`は`Height: 100%`で指定しつつボタンを下部に位置させる作りにした方が`ItemDetailCard`のサイズ部分の汎用性も上がると思います！

2023-11-22 03:50 UTC, ryuhei202 commented on app/_components/common/Item/item-detail-card.tsx
> +  withButton,
@ytsumori 修正しました！
<img width="319" alt="スクリーンショット 2023-11-22 12 49 02" src="https://github.com/KiizanKiizan/manene/assets/105505578/df307538-ff33-4286-a6dd-9dce3de44aa1">
<img width="319" alt="スクリーンショット 2023-11-22 12 49 24" src="https://github.com/KiizanKiizan/manene/assets/105505578/356c8272-3d9f-4a6a-b2f9-47018adcaa91">

2023-11-22 03:56 UTC, ytsumori approved these changes
@ryuhei202 
LGTM!!ナイスです〜！

2023-11-24 23:32 UTC, merged