Feature 11 25 コーデピックapiフックスの作成
KiizanKiizan/Manene pull request #32
Opened 2023-07-10 08:08 UTC by kojikojiXX

ご確認よろしくお願いいたします！

2023-07-11 00:33 UTC, ytsumori requested changes
@kojikojiXX ありがとうございます！コメントしたので、確認お願いします！

2023-07-11 00:33 UTC, ytsumori commented on app/model/Host-url.ts
> +  };
[nits]
なんかインデントされちゃってるっぽいんですが、prettier効いてますか？

2023-07-11 00:33 UTC, ytsumori commented on app/api/coorde_pick/useCoordePicksIndex.ts
> +}[];
`axios-case-converter`使ってるんで、レスポンスのプロパティもcamelCaseで合わせた方がいいかなと思いました！

2023-07-11 06:16 UTC, kojikojiXX commented
@ytsumori 修正したので、再度ご確認よろしくお願いします！

2023-07-13 00:58 UTC, ytsumori approved these changes
@kojikojiXX 
ありがとうございマッスル💪

2023-07-13 05:33 UTC, merged