Feature 11 26 コーデピックitemcardsコンポーネントの作成
KiizanKiizan/Manene pull request #35
Opened 2023-07-11 07:38 UTC by kojikojiXX

ご確認よろしくお願いします！

↓画面
![スクリーンショット 2023-07-11 16 36 30](https://github.com/KiizanKiizan/Manene/assets/63447137/1ef458ca-219d-4ead-9929-af5edfc6dae8)
↓モーダル表示
![スクリーンショット 2023-07-11 16 36 58](https://github.com/KiizanKiizan/Manene/assets/63447137/8de810a1-f751-4e36-8a0e-3974bb41d4e5)

2023-07-12 02:19 UTC, kotaesaki requested changes

2023-07-12 02:19 UTC, kotaesaki commented on public/images/item-image/1.webp
IMO: これテスト用だと思うので差分に必要ないと思いました！

2023-07-12 02:19 UTC, kotaesaki commented on app/coorde-pick/page.tsx
> +    <ItemCard imagePath={imagePath}>
nits: これも動作確認用ですかね？差分として必要ないかなと！

2023-07-12 02:19 UTC, kotaesaki commented on app/components/common/Image/expandable-image.tsx
> +import { useState } from "react";
q: これuse clientないですが動作しますか？👀

2023-07-12 02:19 UTC, kotaesaki commented on app/components/common/Image/expandable-image.tsx
> +          aria-labelledby="modal-modal-title"
nits: aria-labelledby, aria-describedbyの値そのままになってます！

2023-07-12 02:19 UTC, kotaesaki commented on app/components/common/Image/image-alt.tsx
> +export default function ImageAlt({
IMO: このコンポーネント"next/image"のImageと全く同じなので必要ないと思いました！

2023-07-12 02:20 UTC, kotaesaki commented
ありがとうございます！コメントしました！

2023-07-13 05:46 UTC, kojikojiXX commented on app/components/common/Image/expandable-image.tsx
> +import { useState } from "react";
動作してます!
あとNext.jsのドキュメントで下記のように言っているのですが、これって、親で"use client"を定義したら、子に書かなくていいってことですよね？
commonのcomponentってどこからか呼ばれるものだと思うので、"use client"を記述しなくていいかなと思いました！

![スクリーンショット 2023-07-13 14 44 03](https://github.com/KiizanKiizan/Manene/assets/63447137/6cb982ce-0f35-45d6-9d80-bf5de3309de7)

2023-07-13 07:29 UTC, kotaesaki commented on app/components/common/Image/expandable-image.tsx
> +import { useState } from "react";
@kojikojiXX 
ありがとうございます！
それだとSCでこのコンポーネントを使われる想定ができないと思いますがどうでしょうか？👀

2023-07-14 01:11 UTC, kojikojiXX commented
@kotaesaki 
app/components/common/Item/item-card.tsx も共通コンポーネントでmuiを使用していたので、"use client"を追加しました!
再度、レビューよろしくお願いします！

2023-07-14 06:54 UTC, kotaesaki commented
@kojikojiXX 
ありがとうございます！
LGTM!!!!!💯

2023-07-14 06:55 UTC, kotaesaki approved these changes

2023-07-15 02:24 UTC, merged