Feature/11 27 コーデピックbarcordidinputtsx作成
KiizanKiizan/Manene pull request #43
Opened 2023-07-13 06:45 UTC by kojikojiXX

レビューよろしくお願いします！

2023-07-14 00:29 UTC, ytsumori requested changes
ありがとうございます！いい感じっすね！
コメントしたので確認お願いします！

2023-07-14 00:29 UTC, ytsumori commented on app/components/common/barcode/barcodeInput.tsx
> +    <Box
muiのDialogコンポーネントを使用するのがいいかなと思いました！
https://mui.com/material-ui/react-dialog/

2023-07-14 00:29 UTC, ytsumori commented on app/components/common/barcode/barcodeInput.tsx
> +  onClickSetChartId: (chartId: number) => void;
`BarcodeInput`コンポーネント自身は入力された値が`chartId`かどうかを理解していないので、引数とcallbackの命名に`chartId`は含めない方が良いかと思いました！

2023-07-14 00:58 UTC, kotaesaki commented
projectとissueと紐づいていない？🤔

2023-07-14 01:42 UTC, kojikojiXX commented on app/components/common/barcode/barcodeInput.tsx
> +    <Box
@ytsumori 
今回はダイアログの中身を作っただけなので、ダイアログを使用するところでダイアログコンポーネントとボタンを使用しようと思うのですが、
どうでしょうか？

2023-07-14 05:19 UTC, ytsumori reviewed
確認お願いします！

2023-07-14 05:19 UTC, ytsumori commented on app/components/common/barcode/barcodeInput.tsx
> +    <Box
@kojikojiXX 
なるほど！
であれば`position`や`transform`属性は指定しない方がいいですね！それらをMUIのDialogコンポーネントがよしなにやってくれると思うので任せましょう！
あとレスポンシブ対応の観点でも、できるだけMUIが提供してくれてるものを使う方が設定が楽になるかなと思います！

2023-07-14 07:33 UTC, kojikojiXX commented
@ytsumori 
Dialogを使用して修正しました。デザインも変わったので、確認よろしくお願いします！

↓変更後
![スクリーンショット 2023-07-14 16 30 54](https://github.com/KiizanKiizan/Manene/assets/63447137/8145b68d-ef9b-4c17-90b3-b9daf9cd8bd3)

2023-07-18 00:08 UTC, ytsumori requested changes
追加でコメントしました！
確認よろしくお願いします！

2023-07-18 00:08 UTC, ytsumori commented on app/components/common/barcode/barcodeInput.tsx
> +        <Button onClick={() => onClickSetId(parseInt(id))}>OK</Button>
`parseInt`を使うと`NaN`が返ってきてしまう可能性があるので、その場合にもコールバックを実行してしまうと想定しない動きが発生しちゃいそうかなと思います！

また、このフォーム入力はリアルタイムでバリデートしていいと思うので、`id`stateはnumber型で定義して制限した上で、`TextField`の`onChange`の処理で数字じゃなければ`setState`を実行しないように実装するのもいいかなと思いました！

2023-07-18 02:30 UTC, ryuhei202 commented on app/components/common/barcode/barcodeInput.tsx
> +        <Button onClick={() => onClickSetId(parseInt(id))}>OK</Button>
@ytsumori 
id入力の実装なんですけど、僕もいくつか考えてみて今回のtype="number"にしてstringをparseIntする実装に至りました。そもそもTextfieldのevent.target.valueの値が、数値だとしてもstringで渡ってくるのるので少し戸惑いました。
いくつかの候補をここに挙げます!
1と3で悩んだんですが、実装の簡易さ、ユーザービリティの向上から1を選択しました！数字以外入れれないからNaNにはならないかなーと思ってます！
どうでしょうか？

**1. type="number"にして数字だけを受け入れる。(今回の実装)**

メリット:
数字のみが入力できないようになる。

開いた時から数字のキーボードになっている。

デメリット:
Textfieldのevent.target.valueにはstringとして渡ってくるため、stateをstirng型で受け入れ、それをonClickイベントの引数にparseIntしてnumber型にする必要がある。

数値以外入力すらできず、ペーストもできないため困惑する人もいそう

NaNの可能性(数字以外入れれないからNaNにはならなさそう？)

**2. バリデーションをかけstateをセットするかを制限する。(津守さんの提案)**
メリット:
 バリデーションをかけたうえで、parseIntしてstateの型をnumber型にできるので型の整合性が取れる

デメリット
文字を入力してもsetされないので、入力欄の値と実際のstateの値が一致しない

開いた時は文字のキーボード

**3.  stateをstringで受け入れ、バリデーションをかけてエラーメッセージと一緒に管理し、errorがあるときはdisableにする(Ohrotのフォームの実装)**

メリット
エラーメッセージが出るためわかりやすい。

何がきてもsetはするため入力欄の値とstateの値は一致する。ただしバリデーションをかけるためエラーがあればOKは押せない。

デメリット
開いた時は文字のキーボード

2023-07-18 23:19 UTC, ytsumori commented on app/components/common/barcode/barcodeInput.tsx
> +        <Button onClick={() => onClickSetId(parseInt(id))}>OK</Button>
@ryuhei202 
僕の提案は1の状態で2を適用して型補完の恩恵も受けれるようにしちゃおうって意味でした！
そして2の
> デメリット
文字を入力してもsetされないので、入力欄の値と実際のstateの値が一致しない

に関しては表示する値がstateの値なので、数字以外を入れても表示されないしstateにも反映されないかなと！（そしてこれがcomponentをcontrolledにしておきたい理由です！）

2023-07-20 03:44 UTC, kojikojiXX commented
@ytsumori 
修正したので、確認お願いします！

2023-07-21 01:43 UTC, ytsumori approved these changes
@kojikojiXX 
ありがとうございます！LGTM！
一件コメントしましたが、nitなのでapproveしておきます！

2023-07-21 01:43 UTC, ytsumori commented on app/components/common/barcode/barcode-input-dialog.tsx
> +        <Button onClick={() => onClickSetId(id as number)} disabled={!id}>
@kojikojiXX 
[nits]
idはnumber型なので型アサーションは不要かなと思いました！

2023-07-21 02:53 UTC, merged