feat: プロダクション環境では特定のipアドレスでしかアクセスできないようにする
KiizanKiizan/Manene pull request #45
Opened 2023-07-14 05:58 UTC by ryuhei202

ご確認お願いします！

2023-07-18 00:13 UTC, ytsumori commented on middleware.ts
> +  process.env.NEXT_PUBLIC_VPN ?? "", //VPN
@ryuhei202
質問: 今後VPNなどを追加して許可したいIPアドレスが増えていきそうなんですが、この実装で複数のIP指定って可能ですか？

2023-07-18 01:31 UTC, ryuhei202 commented on middleware.ts
> +  process.env.NEXT_PUBLIC_VPN ?? "", //VPN
@ytsumori 環境変数を増やす必要があると思います！VPN1とかの名前にした方が良さそうですかね？

2023-07-18 02:38 UTC, ytsumori requested changes

2023-07-18 02:38 UTC, ytsumori commented on middleware.ts
> +  process.env.NEXT_PUBLIC_VPN ?? "", //VPN
@ryuhei202 
複数指定できるようにしたいです！vercel側でIP足せばコード触らずに許可できるようにしたいので！

2023-07-24 09:08 UTC, ryuhei202 commented on middleware.ts
> +  process.env.NEXT_PUBLIC_VPN ?? "", //VPN
@ytsumori 環境変数に新しいVPNを追加する場合、コードも追加する必要があると思うのですが、コード追加せずにvercel側だけで完結しようとする場合、以下のようなイメージで大丈夫でしょうか？

> vercelの環境変数において、一つのkeyに対して配列で複数の値を管理することはできる？

ChatGPT
Vercelの環境変数は文字列形式で保存されるため、直接配列として保存することはできません。しかし、文字列として配列を表現し、アプリケーションの中でそれを解析するという方法があります。

たとえば、JavaScriptでは以下のように環境変数を管理することができます。

arduino
Copy code
// 環境変数を設定
VERCEL_VARIABLE="value1,value2,value3"

// アプリケーションで解析
const array = process.env.VERCEL_VARIABLE.split(',');
上記の例では、環境変数VERCEL_VARIABLEに文字列"value1,value2,value3"を設定しています。その後、アプリケーション内でこれを解析するために、split関数を使用して文字列をカンマで分割し、配列を取得します。

注意点として、この方法は、環境変数の値が文字列であり、カンマや使用する分割文字が環境変数の値に含まれないことを前提としています。

もし環境変数が複雑なデータ構造を持つ場合は、JSON形式を利用して保存し、アプリケーション側でそれをパースするという方法も考えられます。ただし、この方法もエスケープが必要な文字などの管理が必要になりますし、長すぎる環境変数は一部のシステムで問題を引き起こす可能性があるので注意が必要です。

2023-07-24 23:36 UTC, ryuhei202 commented on middleware.ts
> +  process.env.NEXT_PUBLIC_VPN ?? "", //VPN
環境変数をVPN_1とかVPN_2とかにして繰り返し処理とかでもいけそう

2023-07-28 04:47 UTC, ryuhei202 commented
@ytsumori これVPNをmapで繰り返したので、vercel側で増やせばコード触らなくても良くなりました！
マージして確認したいです！

2023-08-10 02:48 UTC, ytsumori commented
こちら今優先順位下がってるので、一旦クローズしちゃいます！

2023-08-10 02:48 UTC, ytsumori commented
こちら今優先順位下がってるので、一旦クローズしちゃいます！

2023-08-10 02:48 UTC, closed without merging