Feature/11 50 ホーム画面の実装
KiizanKiizan/Manene pull request #52
Opened 2023-07-19 09:17 UTC by kojikojiXX

ホーム画面の実装

- MUIのAccordionを使って、メニューバーを閉じれるようにした。
- reactRouterを使って画面遷移の実装をした。

https://github.com/KiizanKiizan/Manene/assets/63447137/b663a3e9-faaf-4a5d-9e81-af7eaea6b6ba

2023-07-20 00:12 UTC, kotaesaki approved these changes

2023-07-20 00:12 UTC, kotaesaki commented on app/components/common/button/link-button.tsx
> +    <>
nits: 子要素が一つしかない場合はFragment```<></>```必要ないです！

2023-07-20 00:12 UTC, kotaesaki commented on app/page.tsx
nits: 動画見た感じ、外側にmarginかpaddingがついているのが少し気になりました！

2023-07-20 00:12 UTC, kotaesaki commented
@kojikojiXX ありがとうございます！コメントしましたがnitsなので承認します！👏

2023-07-20 01:17 UTC, kojikojiXX commented on app/page.tsx
@kotaesaki 
画面録画の範囲指定だと思います。すみません🙇‍♂️
再度撮ったので、ご確認お願いします！

2023-07-20 01:23 UTC, ryuhei202 requested changes
ありがとうございます！見た目もめちゃくちゃいい感じです👍
コメントしたので確認おねがします！

2023-07-20 01:23 UTC, ryuhei202 commented on app/components/common/accordion/menu-accordion.tsx
> +  const theme = useTheme();
themeの設定ってどこのファイルでしてます？🤔（初期の青色使ってるから設定いらないのかな？）

2023-07-20 01:23 UTC, ryuhei202 commented on app/page.tsx
> +export default function home() {
[IMO]home → HomePage
コーディングルールに書いてなかったですが、page.tsxは基本的に、ディレクトリ名Pageがよろしいかと！例)CoordePickPage
今回はトップレベルのpage.tsxなのでディレクトリ名は存在しませんが、ホームのページの役割を持っているのでHomePageで!

2023-07-20 01:24 UTC, ryuhei202 commented on app/page.tsx
> +      <AppBar position="static">
Appbarいったんなしでお願いします！

2023-07-25 09:22 UTC, ryuhei202 approved these changes
@kojikojiXX 確認しました！ありがとうございます！

2023-07-29 03:31 UTC, ryuhei202 commented
@kojikojiXX これもマージしちゃって大丈夫です！

2023-07-31 00:40 UTC, merged