Feature/11 53 トップレベルのlayouttsxにヘッダーを移行
KiizanKiizan/Manene pull request #63
Opened 2023-07-25 02:59 UTC by kojikojiXX

ヘッダーをtopのlayout.tsxで管理する。
usecontextでページのパスごとに、ヘッダーに表示する文言を動的にした。

2023-07-25 09:56 UTC, ryuhei202 requested changes
@kojikojiXX ありがとうございます！いくつかコメントしました！
それと実際にヘッダーのタイトルが変わっている動画もあったら嬉しいです！

2023-07-25 09:56 UTC, ryuhei202 commented on app/model/shared/pathname.ts
> +    case "/coorde_pick":
urlを変えて画面遷移する場合、`/coorde_pick/12345/hoge`とかになると思うんですけど、その場合でも「コーデピック」と出て欲しいので条件文を正規表現でテストするのがいいとおもいましたがどうでしょうか？

2023-07-25 09:56 UTC, ryuhei202 commented on app/layout.tsx
> +        </AppBarContextProvider>
ProvidersコンポーネントにAppBarContextProviderも含めちゃえばいいと思いました！

2023-07-26 06:35 UTC, kojikojiXX commented on app/model/shared/pathname.ts
> +    case "/coorde_pick":
@ryuhei202 
確かにそうですね！
実装します！

2023-07-26 06:37 UTC, kojikojiXX commented on app/layout.tsx
> +        </AppBarContextProvider>
@ryuhei202 
そうすると、useContextを使用するHeaderコンポーネントもProvidersコンポーネントに入れる必要が出てくるのですが、そういうことでしょうか？

2023-07-27 07:14 UTC, ryuhei202 commented on app/layout.tsx
> +        </AppBarContextProvider>
@kojikojiXX そうですね！こんな感じでいけないでしょうか？
```
<Providers>
  <Header />
  {children}
</Providers>
```

2023-07-27 07:15 UTC, ryuhei202 commented on app/model/shared/pathname.ts
> +    case "/coorde_pick":
case文だと条件分書けないかも~

2023-07-31 04:11 UTC, closed without merging