Feature 62 74 忘れ物apiフックス作成
KiizanKiizan/Manene pull request #77
Opened 2023-07-31 08:10 UTC by yusei53

ご確認よろしくお願いします！

2023-07-31 11:09 UTC, ytsumori approved these changes
ナイス初PR！LGTMです！

2023-08-01 00:33 UTC, ryuhei202 requested changes

2023-08-01 00:45 UTC, yusei53 commented
@ryuhei202  [13a5c11](https://github.com/KiizanKiizan/Manene/pull/77/commits/13a5c11c75931653cb0b0b74e24ada4ab89c6765) レビュー対応致しました。ご確認よろしくお願い致します。

2023-08-03 01:11 UTC, ryuhei202 commented
@yusei53 確認しました！ありがとうございます！

2023-08-03 01:11 UTC, ryuhei202 approved these changes

2023-08-03 02:49 UTC, merged