Feature/61 78 lostarticlesdialogs作成
KiizanKiizan/Manene pull request #82
Opened 2023-08-01 04:09 UTC by yusei53

お手隙の際、ご確認よろしくお願い致します。

![スクリーンショット 2023-08-01 13 03 48](https://github.com/KiizanKiizan/Manene/assets/108526619/476c194d-eadf-4691-8b30-cad614557eb9)
![スクリーンショット 2023-08-01 13 03 27](https://github.com/KiizanKiizan/Manene/assets/108526619/625b7c87-98b9-4e90-ad4d-a2e0010ab684)

2023-08-02 01:12 UTC, kotaesaki requested changes
ありがとうございます！いい感じです！
何件かコメントしましたのでご確認お願いします！

2023-08-02 01:12 UTC, kotaesaki commented on app/components/lost_articles/lost-articles-dialogs.tsx
> +  swichOpenConfirmDialog: () => void;
typo: 

```
💩swichOpenConfirmDialog
✅swtichOpenConfirmDialog
```

↓追加しましょう！`vscode/extensions.json`にも追加してもらえるとプロジェクトのおすすめ拡張になるので入れといていいかもしれないです！

Name: Code Spell Checker
Id: streetsidesoftware.code-spell-checker
Description: Spelling checker for source code
Version: 2.20.5
Publisher: Street Side Software
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2023-08-02 01:12 UTC, kotaesaki commented on app/components/lost_articles/lost-articles-dialogs.tsx
> +  swichOpenConfirmDialog: () => void;
nits: 
この関数ってDialogを閉じるための関数ですかね？🤔
だとしたら名前が少し分かりづらいと思いました！

`onClickCancel`などでいいかなと！

2023-08-02 01:12 UTC, kotaesaki commented on app/components/lost_articles/lost-articles-dialogs.tsx
> +    swichOpenConfirmDialog();
q: useEffectしている理由ってなんでしょうか？👀

2023-08-02 01:12 UTC, kotaesaki commented on app/components/lost_articles/lost-articles-dialogs.tsx
> +      <Dialog open={isOpenConfirmDialog} fullWidth={true}>
IMO: それぞれのDialogでrenderし直すよりかは、Dialogの中身出し分けるようがいいかと思いました！この実装だと両方のDialogが表示されるような不具合を潜ませていると思います！

2023-08-02 01:12 UTC, kotaesaki commented on app/components/lost_articles/lost-articles-dialogs.tsx
> +      <Dialog open={isOpenConfirmDialog} fullWidth={true}>
nits: 
trueの場合は省略できます！

```
💩fullWidth={true}
✅fullWidth
```

2023-08-03 00:39 UTC, ryuhei202 commented on app/components/lost_articles/lost-articles-dialogs.tsx
> +      <Dialog open={isOpenConfirmDialog} fullWidth={true}>
> IMO: それぞれのDialogでrenderし直すよりかは、Dialogの中身出し分けるようがいいかと思いました！この実装だと両方のDialogが表示されるような不具合を潜ませていると思います！

確かーに！実装しながらもやもやしてたの解決した！`isOpenConfirmDialog`いらないな！

2023-08-03 02:53 UTC, kotaesaki approved these changes
ありがとうございます！ LGTM!!!

2023-08-03 03:20 UTC, merged