feat: Html5QrcodeScannerライブラリを使用して、QRコードリーダー作成
KiizanKiizan/Manene pull request #84
Opened 2023-08-01 08:55 UTC by kojikojiXX

2023-08-02 01:38 UTC, kotaesaki requested changes

2023-08-02 01:38 UTC, kotaesaki commented on package.json
今まで使っていた`react-qr-reader`はまだ必要そうですか？👀
必要ないなら消しちゃって問題ないかと！

2023-08-02 01:38 UTC, kotaesaki commented on app/components/common/barcode/qr-code-reader.tsx
> +    const hh = "";
q: ライブラリの僕の理解不足もあってhhが必要な理由がわからなかったんですが、これだと全てtrueで返ってしまいませんか？🤔

2023-08-02 01:39 UTC, kotaesaki commented
ありがとうございます！一点質問させていただきました！
これでアイテムのバーコード取得できそうでした？👀

2023-08-04 02:16 UTC, kojikojiXX commented on app/components/common/barcode/qr-code-reader.tsx
> +    const hh = "";
@kotaesaki 
修正しました!

2023-08-04 02:17 UTC, kojikojiXX commented
@kotaesaki 
修正したので、再度確認よろしくお願いします！
バーコード取得できそうです！

2023-08-04 03:23 UTC, kotaesaki submitted a review, later dismissed
ありがとうございます！LGTM!!

2023-08-07 01:49 UTC, kotaesaki approved these changes

2023-08-07 08:46 UTC, merged